language: rust
cache: /tmp/travis/cargo/jsonwatch/
addons:
  apt:
    packages:
      - expect
      - musl-tools
      - tcl
before_install:
  - rustup target add x86_64-unknown-linux-musl
script:
  - make test
