[package]
name = "jsonwatch"
version = "0.5.0"
authors = ["D. Bohdan <dbohdan@dbohdan.com>"]
edition = "2018"

[dependencies]
chrono = "~0.4"
clap = "~2.33"
serde_json = {features = ["preserve_order"], version = "~1.0"}
ureq = "~0.11"
