name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies with APT
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get install -y expect

    - name: Remove Expect for Tcl 8.5
      if: matrix.os == 'macos-latest'
      run: |
        brew uninstall expect

    - name: Set up MacPorts
      if: matrix.os == 'macos-latest'
      uses: melusina-org/setup-macports@v1

    - name: Install Expect for Tcl 8.6
      if: matrix.os == 'macos-latest'
      run: |
        port install expect

    - name: Set up just
      uses: extractions/setup-just@v2

    - name: Run tests
      run: |
        just test
